**Humpty Dumpty**

In [ ]:
def Humpty_Dumpty(number):
    if number % 3 == 0 and number % 5 == 0:
        return "Humpty_Dumpty"
    elif number % 3 == 0:
        return "Humpty"
    elif number % 5 == 0:
        return "Dumpty"
    else:
        return number


num = int(input("Enter a number: "))
result = Humpty_Dumpty(num)
print(result)

Enter a number: 5
Dumpty


**Matrix Multiplication**

In [ ]:
import numpy as np
matrix_a = np.array([[1, 2],[3, 4],[5, 6]])
matrix_b = np.array([[7, 8, 9],[10, 11, 12]])
result = np.dot(matrix_a, matrix_b)

print("Matrix_a:")
print(matrix_a)
print("Matrix_b:")
print(matrix_b)
print("Result of matrix multiplication:")
print(result)


Matrix_a:
[[1 2]
 [3 4]
 [5 6]]
Matrix_b:
[[ 7  8  9]
 [10 11 12]]
Result of matrix multiplication:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


**Returns sum of multiples**

In [ ]:
def sum_of_multiples(limit):
    result = 0
    for num in range(limit + 1):
        if num % 3 == 0 or num % 5 == 0:
            result += num
    return result

limit = int(input("Enter the limit: "))
total_sum = sum_of_multiples(limit)
print(f"The sum of multiples of 3 and 5 between 0 and {limit} is:{total_sum}")

Enter the limit: 8
The sum of multiples of 3 and 5 between 0 and 8 is:14


**Read and plot**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
data = np.loadtxt ('/content/drive/MyDrive/data.txt')
plt.plot(data[:, 0], data[:, 1])
plt.title('Data from data.txt')
plt.xlabel('X')
plt.ylabel('Y')
m, c = np.polyfit(data[:, 0], data[:, 1], 1)
plt.plot(data[:, 0], m*data[:, 0] + c, color='green')
plt.show()

NameError: ignored